# baseURL = "http://www.familyandfinancialtherapy.com.s3-website-us-east-1.amazonaws.com/"
baseURL = '/'
themesDir = "themes"
theme = "hugo-serif-theme"
languageCode = "en-us"
title = "Family and Financial Therapy"

[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""

  [params.logo]
    # mobile = "images/logo-mobile.svg"
    standard  = "images/logo.png"
    alt = "Family and Financial Therapy"

  [params.homepage_meta_tags]
    meta_description = "Family and Financial Therapy is a small business dedicated to helping individuals and families have healthier mental and financial lives."
    meta_og_title = "Family and Financial Therapy"
    meta_og_type = "website"
    meta_og_url = "https://hugo-serif.netlify.com"
    # meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
    meta_og_description = "Family and Financial Therapy is a small business dedicated to helping individuals and families have healthier mental and financial lives."
    meta_twitter_card = ""
    meta_twitter_site = ""
    meta_twitter_creator = ""

[menu]
  # Main Menu
  [[menu.main]]
    name = "Services"
    url = "/services/"
      weight = 1

  [[menu.main]]
      name = "About"
      url = "/team/"
      weight = 2

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Contact"
    url = "/contact/"
      weight = 2


[[resources]]
  name = "client_info"
  src = "/docs/client_info.pdf"
  [resources.params]
    icon = "pdf"

[deployment]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
order = [".jpg$", ".gif$"]

  [[deployment.targets]]
  # An arbitrary name for this target.
  name = "aws"
  # The Go Cloud Development Kit URL to deploy to. Examples:
  # GCS; see https://gocloud.dev/howto/blob/#gcs
  # URL = "gs://<Bucket Name>"

  # S3; see https://gocloud.dev/howto/blob/#s3
  # For S3-compatible endpoints, see https://gocloud.dev/howto/blob/#s3-compatible
  URL = "s3://www.familyandfinancialtherapy.com?region=us-east-1"
